### ISSUE TITLE
go lang tidak ada output setelah run

### ISSUE THREAD

**Issue by satrioaw** [Go-ID-community/go-tour-id#2]
saya tes di go tutorial di window sebelah kanan tidak ada output di semua tutorial, setelah run.

**Comment by shuLhan** [comment]
Sepertinya semua situs tur selain yang resmi (tour.golang.org) memiliki masalah yang sama. Saya sudah coba dengan versi yang bahasa Prancis dan Brazil, situs itu juga tidak bisa menjalankan contoh kode setelah Run.

Saya sudah laporkan masalah ini ke situs utama [1], nanti kalau sudah ada perbaikan dari mereka saya kabarkan lagi. Terima kasih atas laporannya.

[1] golang/go#15693

**Comment by shuLhan** [comment]
Tur yang baru sudah dideploy ulang. Silahkan dicoba lagi.
