### ISSUE TITLE
tur: missing return at end of function

### ISSUE THREAD

**Issue by lamualfa** [Go-ID-community/go-tour-id#7]
Konteks: https://go-tour-id2.appspot.com/moretypes/18

Code:
```
package main

import "golang.org/x/tour/pic"

func Pic(dx, dy int) [][]uint8 {
}

func main() {
	pic.Show(Pic)
}
```
I get error from output after run the program:

```
prog.go:6:1: missing return at end of function

Program exited.
```

**Comment by shuLhan** [comment]
Would you like to send pull request (PR)?

**Comment by lamualfa** [comment]
> Would you like to send pull request (PR)
Saya pikir Error diatas Hanya Di sebabkan karena fungsi `Pic` tidak memiliki syntax Yang akan dieksekusi sehingga tidak ada return yang di jalankan.

**Comment by lamualfa** [comment]
> Would you like to send pull request (PR)?

Besok akan saya buatkan PR nya kalau perlu

**Comment by shuLhan** [comment]
Bentar, fungsi `Pic()` itu memang sengaja kosong dan tanpa `return` statement karena halaman tersebut untuk latihan bagi pembaca.

Jadi, pembaca tur diharapkan mengisi body dari fungsi `Pic()`.

**Comment by lamualfa** [comment]
Oh pantes, saya nggak baca perintahnya. Maaf merepotkan.Tolong di hapus issue nya.

**Comment by shuLhan** [comment]
@laodelmafatih, tidak apa-apa, selamat belajar Go ya.
